[default.extend-words]
iddeal = "ideal"
iddeals = "ideals"
allpha = "alpha"

# strings that are not a typo:
thm = "thm"

# equations stuff
ba = "ba"
nd = "nd"

# names
Strang = "Strang"
Bootle = "Bootle"
