# usage:
# install `typos`: https://github.com/crate-ci/typos
# run: typos -c .github/workflows/typos.toml

[default.extend-words]
iddeal = "ideal"
iddeals = "ideals"
allpha = "alpha"
fieldd = "field"

# strings that are not a typo:
thm = "thm"

# equations stuff
ba = "ba"
nd = "nd"

# names
Strang = "Strang"
Pinter = "Pinter"
Bootle = "Bootle"
Groth = "Groth"
